import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { format } from 'date-fns';

export const generateInvoicePDF = (invoice, userProfile) => {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const primary = [79, 70, 229];   // #4F46E5 as RGB
  const dark    = [30, 41, 59];
  const gray    = [100, 116, 139];
  const W = doc.internal.pageSize.getWidth();

  const symbols = { INR: 'Rs ', USD: '$', EUR: 'E ' };
  const sym = symbols[invoice.currency] || 'Rs ';

  // ── Header band ─────────────────────────────────────
  doc.setFillColor(...primary);
  doc.rect(0, 0, W, 38, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.text('FreelanceFlow', 14, 16);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(userProfile.name || '',  14, 24);
  doc.text(userProfile.email || '', 14, 30);

  // INVOICE label right side
  doc.setFontSize(28);
  doc.setFont('helvetica', 'bold');
  doc.text('INVOICE', W - 14, 20, { align: 'right' });
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.text(invoice.invoice_number, W - 14, 30, { align: 'right' });

  // ── Invoice meta ─────────────────────────────────────
  doc.setTextColor(...dark);
  doc.setFontSize(9);
  doc.text(`Issue Date: ${format(new Date(invoice.issue_date), 'dd MMM yyyy')}`, W - 14, 48, { align: 'right' });
  doc.text(`Due Date:   ${format(new Date(invoice.due_date),  'dd MMM yyyy')}`, W - 14, 54, { align: 'right' });

  // ── Bill To ────────────────────────────────────────
  doc.setFontSize(8);
  doc.setTextColor(...gray);
  doc.text('BILL TO', 14, 48);
  doc.setFontSize(11);
  doc.setTextColor(...dark);
  doc.setFont('helvetica', 'bold');
  doc.text(invoice.client_name,    14, 56);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  if (invoice.client_company) doc.text(invoice.client_company, 14, 62);
  if (invoice.client_email)   doc.text(invoice.client_email,   14, 68);

  // ── Items table ────────────────────────────────────
  autoTable(doc, {
    startY: 78,
    head: [['Description', 'Rate', 'Amount']],
    body: invoice.items.map(item => [
      item.project_name || item.description,
      `${sym}${parseFloat(item.rate).toFixed(2)}`,
      `${sym}${parseFloat(item.amount).toFixed(2)}`,
    ]),
    headStyles: {
      fillColor: primary, textColor: [255,255,255], fontStyle: 'bold', fontSize: 9,
    },
    bodyStyles: { fontSize: 9, textColor: dark },
    alternateRowStyles: { fillColor: [248,250,252] },
    columnStyles: {
      0: { cellWidth: 'auto' },
      1: { halign: 'right', cellWidth: 35 },
      2: { halign: 'right', cellWidth: 40 },
    },
    margin: { left: 14, right: 14 },
  });

  // ── Totals ────────────────────────────────────────
  const finalY = doc.lastAutoTable.finalY + 8;
  const totalsX = W - 80;
  doc.setFontSize(9);
  doc.setTextColor(...gray);
  doc.text('Subtotal', totalsX, finalY);
  doc.setTextColor(...dark);
  doc.text(`${sym}${parseFloat(invoice.subtotal).toFixed(2)}`, W - 14, finalY, { align: 'right' });

  doc.setTextColor(...gray);
  doc.text(`GST (${invoice.tax_rate}%)`, totalsX, finalY + 7);
  doc.setTextColor(...dark);
  doc.text(`${sym}${parseFloat(invoice.tax_amount).toFixed(2)}`, W - 14, finalY + 7, { align: 'right' });

  // Total highlight box
  doc.setFillColor(...primary);
  doc.roundedRect(totalsX - 4, finalY + 12, W - totalsX + 4 - 10, 12, 2, 2, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text('TOTAL', totalsX, finalY + 21);
  doc.text(`${sym}${parseFloat(invoice.total).toFixed(2)}`, W - 14, finalY + 21, { align: 'right' });

  // ── Footer ────────────────────────────────────────
  doc.setFontSize(8);
  doc.setTextColor(...gray);
  doc.setFont('helvetica', 'normal');
  if (invoice.notes) {
    doc.text('Notes:', 14, finalY + 36);
    doc.setTextColor(...dark);
    doc.text(invoice.notes, 14, finalY + 42);
  }
  doc.setTextColor(...gray);
  doc.text('Generated by FreelanceFlow', W / 2, doc.internal.pageSize.getHeight() - 10, { align: 'center' });

  doc.save(`${invoice.invoice_number}.pdf`);
};
